version: '2'
services:
#  client:
#   image: my_client
#   links:
#     - server:server
  server:
   image: my_server
   ports:
     - "8001:80"
   links:
     - mysql:mysql
     - rabbit:rabbit
   volumes:
#    - ./logs/worker:/var/log/oasis
     - ./upload:/var/www/oasis/upload
     - ./download:/var/www/oasis/download
  worker_1:
    image: my_worker
    links:
     - mysql:mysql
     - rabbit:myrabbit
    volumes:
#      - ./logs/worker:/var/log/oasis
     - ./upload:/var/www/oasis/upload
     - ./download:/var/www/oasis/download
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery 
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  flower:
    image: iserko/docker-celery-flower 
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672
    entrypoint:
      - flower 
      - --port=5555 
      - --broker_api=http://guest:guest@rabbit:5672/api/"
    links:
     - mysql
     - rabbit