version: '2'
services:
  runner:
   image: api_runner
   links:
    - server:oasis_api_server
  server:
   image: oasis_api_server
   ports:
     - "8001:80"
   environment:
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
   volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
  worker:
    image: model_execution_worker
    environment:
     - MODEL_SUPPLIER_ID=OasisIM
     - MODEL_VERSION_ID=1
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
     - LOCK_FILE = '/tmp/tmp_ktools_lock_file'
     - DO_CLEAR_WORKING = True
     - KTOOLS_BATCH_COUNT=-1
    volumes:
#     - ./log:/var/log/oasis:rw
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
     - ./data/static:/var/oasis/model_data/OasisIM/1:rw
  oasis_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery 
  oasis_rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
