version: '2' 
services:

  oasis_model_execution_worker:
    restart: always
    image: coreoasis/model_execution_worker:__oasis_release_tag__
    container_name: oasis_worker
    volumes:
     - ./upload:/var/www/oasis/upload:rw
     - ./download:/var/www/oasis/download:rw
     - ./model_data:/var/oasis/model_data/__model_supplier__/__model_version__:rw
     - /tmp:/tmp
    extra_hosts:
     - oasis_mysql:__ip_address__
     - oasis_rabbit:__ip_address__
    environment:
     - OASIS_KTOOLS_BATCH_COUNT=-1
     - OASIS_MODEL_SUPPLIER_ID=__model_supplier__
     - OASIS_MODEL_VERSION_ID=__model_version__
     - OASIS_LOCK_FILE='/tmp/tmp_ktools_lock_file'
     - OASIS_RABBIT_PORT=5672
     - OASIS_MYSQL_PORT=3306
